mysns:
  comment-first-limit: 5

spring:

  messages:
    basename: messages,errors

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: 1234
    username: postgres

#    url: jdbc:mysql://localhost:3306/test
#    targetUsername: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect

  batch:
    jdbc.initialize-schema: always
    job.enabled: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: oauth2
            clientSecret: dAjea8o8aFdte09SI9A9sSxRYF8WAmDn
            scope:
              - openid
              - profile
              - email
        #          google:
        #            clientId: 123
        #            clientSecret: 1233
        provider:
          keycloak:
            issuerUri: http://localhost:3333/realms/master
#
  servlet:
    multipart:
      max-file-size: 7MB
#      enabled: false

logging.level.io.awspring.cloud: debug
#logging.level.org.springframework: debug